name: UBansAddon
main: pawarenessc\UBansAddon\Main
version: 1
api: [4.0.0,3.0.0,3.5.0]
author: PawarenessC
load: POSTWORLD
description: UBan
commands:
 ubanad:
  description: "UBansアドオン"
  usage: "/ubanad"
